import { ref, computed, watchEffect } from "vue";

export type Language = "en" | "ar";

const translations = {
  en: {
    all: "All",
    // Navbar
    dashboard: "Dashboard",
    pointOfSale: "Point of Sale",
    stocks: "Stocks",
    pos: "POS",
    inventory: "Inventory",
    marketplace: "Marketplace",
    purchase: "Purchase",
    sellerPXP: "Seller PXP",
    customers: "Customers",
    reports: "Reports",
    settings: "Settings",

    // Inventory Menu
    yourProducts: "Your Products",
    inventoryProductsList: "Inventory Products List",
    createProduct: "Create Product",
    updateStock: "Update Stock",
    manualUpdateStock: "Manual Update Stock",
    openingStock: "Opening Stock",
    createStockAdjustment: "Create Stock Adjustment",
    inventoryAdjustmentHistory: "Inventory Adjustment History",
    printBarcode: "Print Barcode",
    addProduct: "Add Product",
    browseAumetCore: "Browse Aumet Core",
    myProducts: "My Products",
    newProduct: "New Product",
    chooseProductSourceDescription:
      "Choose where you want to add a product from for this manual stock update.",
    sourceAumetCore: "Aumet Core",
    sourceAumetCoreDescription:
      "Browse predefined catalog products from Aumet Core.",
    sourceMyProducts: "My Products",
    sourceMyProductsDescription:
      "Select products that already exist in your inventory.",
    sourceNewProduct: "New Product",
    sourceNewProductDescription:
      "Create a brand-new custom product and add it directly to the table.",
    myProductsDescription:
      "Browse products already available in your inventory and add them to the manual stock table.",
    searchMyProducts:
      "Search by code, product name, barcode, batch, or warehouse...",
    noMyProductsFound: "No inventory products found",
    selectProductsFromInventory:
      "Select one or more products from your inventory to add into the manual stock table.",
    newProductDescription:
      "Create a custom product that is not available in Aumet Core or your inventory.",
    enterProductCode: "Enter product code",
    enterBarcode: "Enter barcode",
    productNameEn: "Product Name EN",
    productNameAr: "Product Name AR",
    enterProductNameEn: "Enter English product name",
    enterProductNameAr: "Enter Arabic product name",
    productCodeAlreadyExists:
      "This product code is already added to the table.",
    customProductWillBeAddedToTable:
      "This product will be added as a normal editable row in the manual stock table.",
    batches: "Batches",
    viewBatches: "View batches",
    collapse: "Collapse",
    expandBatches: "Expand batches",
    collapseBatches: "Collapse batches",
    productMasterAndBatches: "Product Master & Batches",
    editProductAndBatchDetails:
      "Edit product identity and review its batch-level inventory details.",
    selectBatchesOptional: "Select batches (optional)",
    leaveWithoutBatchesToCreateNew:
      "Leave without choosing batches to create a new batch in manual stock.",
    addNewBatch: "Add New Batch",
    newBatch: "New Batch",
    batchNumber: "Batch Number",
    batchDetails: "Batch Details",
    existingBatchesCanBeEdited:
      "Edit existing batches, remove the ones you do not want, or add a new batch.",
    addBatch: "Add Batch",
    editExistingBatch: "Edit Existing Batch",
    selectExistingBatch: "Select Existing Batch",
    chooseBatchToEditAndAdd: "Choose a batch to edit and add it instantly.",
    linked: "Linked",
    notLinked: "Not Linked",
    deleteProduct: "Delete Product",
    noBatchRowsYet: "No batch rows yet.",
    addExistingOrCreateNewBatch: "Add an existing batch or create a new one.",

    productSource: "Source",
    "productSource.core": "Aumet Core",
    "productSource.inventory": "My Products",
    "productSource.custom": "New Product",
    aumetCoreProducts: "Aumet Core Products",
    aumetCoreProductsDescription:
      "Browse predefined pharmacy products and add them to your manual stock table.",
    searchAumetCoreProducts:
      "Search by code, product name, barcode, or manufacturer...",
    selectedItems: "selected",
    manufacturer: "Manufacturer",
    alreadyAdded: "Already added",
    noAumetCoreProductsFound: "No Aumet Core products found",
    selectProductsToAddToManualStock:
      "Select one or more products to add into the manual stock table.",
    addSelectedProducts: "Add Selected Products",
    manualUpdateStockDescription:
      "Manually update stock for selected products using an editable table.",
    manualStockOptions: "Manual Stock Options",
    configureBeforeManualUpdate: "Configure before manual update",
    searchManualStockTable: "Search within selected products...",
    currentStock: "Current Stock",
    adjustmentType: "Adjustment Type",
    stockTypeUpdate: "Stock Type Update",
    stockIn: "Stock In",
    stockOut: "Stock Out",
    newStockQty: "New Stock Qty",
    newStockLevel: "New Stock",
    adjustmentAdd: "Add",
    adjustmentSubtract: "Subtract",
    adjustmentSet: "Set To",
    enterAdjustmentReason: "Enter adjustment reason...",
    manualStockRowsCount: "Rows:",
    saveAdjustments: "Save Adjustments",
    saveAsDraft: "Save as Draft",
    noProductsAddedYet: "No products added yet",
    manualStockEmptyStateDescription:
      "Browse Aumet Core products and add them here to start updating stock manually.",
    loadingMoreProducts: "Loading more products...",

    // Buttons
    createNew: "Create New",
    checkAdjustmentHistory: "Check Adjustment History",
    stockHistory: "Stock History",
    stockAdjustment: "Stock Adjustment",
    review: "Review",
    filters: "Filters",
    export: "Export",

    // Stats
    totalProducts: "Total Products",
    activeProductsInInventory: "Active products in inventory",
    expiringsSoon: "Expiring Soon",
    productsExpiringsNext90Days: "Products expirings next 90 days",
    lowStock: "Low Stock",
    productsBelowMinimumLevel: "Products below minimum level",
    stagnantProducts: "Stagnant Products",
    productsNoSales90Days: "Products with no sales in the last 90+ days",

    // Bulk Stocks Page
    bulkStocksHistory: "Bulk Stocks History",
    trackStocksMovements:
      "Track all stocks movements and changes made to your stock levels",
    updateYourStock: "Update your Stock",
    uploadStockFile: "Upload Stock File",
    createManualList: "Create Manual List",

    // Cards
    receiveMarketplacePurchaseOrders: "Receive Marketplace Purchase Orders",
    new: "New",
    createNewPurchaseOrder: "Create New Purchase Order",
    lastAdded: "Last Added",
    daysAgo: "days ago",

    // Search & Table
    searchByNameIdBarcodeHatch: "Search by name, ID, barcode, batch...",
    code: "Code",
    productName: "Product Name",
    barcode: "Barcode",
    category: "Category",
    lotBatch: "Lot/Batch",
    expiry: "Expiry",
    lastSale: "Last Sale",
    jod: "JOD",
    stockQty: "Stock Qty",
    avgCostPrice: "Avg Cost Price",
    sellPrice: "Sell Price",
    tax: "Tax %",
    warehouseLocation: "Warehouse Location",
    status: "Status",
    actions: "Actions",
    noSales: "No Sales",

    // Pagination
    showing: "Showing",
    to: "to",
    of: "of",
    results: "results",
    show: "Show",
    perPage: "Per Page",
    allResultsOnThisPage: "All 2 results on this page",

    // Footer
    poweredByPulse: "Powered by Pulse - The Heartbeat of Your Pharmacy",
    startTour: "Start Tour",
    help: "Help",

    // Create Product Dialog
    quickNewProductCreation: "Quick New Product Creation",
    quickAddYourProduct: "Quick add your product",
    fillInTheDetailsBelow: "Fill in the details below",
    searchAumetProducts: "Search Aumet Products",
    searchProductName: "Search product name",
    generateBarcode: "Generate",
    enterOrScanBarcode: "Enter, scan, or generate barcode",
    selectCategory: "Select category",
    medicine: "Medicine",
    supplement: "Supplement",
    equipment: "Equipment",
    unitType: "Unit Type",
    selectUnit: "Unit",
    tablet: "Tablet",
    capsule: "Capsule",
    bottle: "Bottle",
    box: "Box",
    count: "Count",
    price: "Price",
    sellingPrice: "Selling Price",
    taxRate: "Tax",
    productDetails: "Product Details",
    firstBatchOptional: "First Batch (Optional)",
    addInitialStock: "Add initial stock",
    warehouse: "Warehouse",
    main: "Main",
    expiryDate: "Expiry Date",
    selectDate: "Select date",
    qty: "Qty",
    cost: "Cost",
    reason: "Reason",
    selectReason: "Select reason",
    newStock: "New Stock",
    restock: "Restock",
    addAnotherBatch: "Add Another Batch",
    moreOptions: "More Options",
    needMoreFields: "Need More Fields? Switch to Full Page",
    back: "Back",
    next: "Next",
    backToChooseProductSource: "Back to choose product source",
    cancel: "Cancel",
    saveProduct: "Save Product",
    fullCreatePageTitle: "Full Product Creation",
    fullCreatePageSubtitle:
      "Create a complete product profile with classification, pricing, media, and visibility settings.",
    fullCreateBreadcrumbCatalog: "Catalog",
    fullCreateBreadcrumbProducts: "Products",
    fullCreateBreadcrumbCreateNew: "Create New",
    fullCreateSaveAndNew: "Save & New",
    fullCreateSaveAndExit: "Save & Exit",
    fullCreateProductType: "Product Type",
    fullCreateNavBasicInfo: "Basic Info",
    fullCreateNavClassification: "Classification",
    fullCreateNavUnitsMix: "Units & Mix",
    fullCreateNavPricingTax: "Pricing & Tax",
    fullCreateNavMedia: "Media",
    fullCreateNavVisibility: "Visibility",
    fullCreateBasicInformation: "Basic Information",
    fullCreateTypeStorable: "Storable",
    fullCreateTypeService: "Service",
    fullCreateTypeConsumable: "Consumable",
    fullCreateBarcodePlaceholder: "Enter barcode or SKU",
    fullCreateAdditionalLanguage: "Additional Language",
    fullCreateAdditionalLanguageNone: "None",
    fullCreateAdditionalLanguageArabic: "Arabic",
    fullCreateAdditionalLanguageFrench: "French",
    fullCreateDefaultLanguage: "Default Language",
    fullCreateDefaultLanguageEnglish: "English (US)",
    fullCreateDefaultLanguageArabic: "Arabic",
    fullCreateDefaultLanguageFrench: "French",
    fullCreateDescription: "Description",
    fullCreateDescriptionPlaceholder: "Brief product description...",
    fullCreateClassification: "Classification",
    fullCreateBrandName: "Brand Name",
    fullCreateBrandNamePlaceholder: "Enter brand name",
    fullCreateVendor: "Vendor",
    fullCreateVendorDirectSource: "Direct Source Inc.",
    fullCreateVendorGlobalLogistics: "Global Logistics Ltd.",
    fullCreateManufacturer: "Manufacturer",
    fullCreateUnitsAndComposition: "Units & Composition",
    fullCreateActiveIngredient: "Active Ingredient",
    fullCreateActiveIngredientsPlural: "Active Ingredients",
    fullCreateSearchPlaceholder: "Search...",
    fullCreateAddIngredient: "Add ingredient",
    fullCreateDosageForm: "Dosage Form",
    fullCreateUomConfiguration: "UOM Configuration",
    fullCreateUomUnitMeasure: "UOM (Unit of Measure)",
    fullCreateUomPack: "Pack",
    fullCreateUomUnit: "Unit",
    fullCreatePackSize: "Pack Size",
    fullCreatePricingAndTax: "Pricing & Tax",
    fullCreateRetailPrice: "Retail Price",
    fullCreateDiscount: "Discount %",
    fullCreateProductMedia: "Product Media",
    fullCreateUploadFiles: "Upload Files",
    fullCreateImageUrl: "Image URL",
    fullCreateUploadHintMain: "Click to upload or drag and drop",
    fullCreateUploadHintSub:
      "PNG, JPG or WEBP (max. 5MB). 800x800px recommended.",
    fullCreateVisibilityTitle: "Status & Visibility",
    fullCreateStatusActions: "Status & Actions",
    fullCreateMandatoryFields: "Mandatory Fields",
    fullCreateMandatoryProductType: "Product Type",
    fullCreateMandatoryBarcodeSku: "Barcode/SKU",
    fullCreateMandatoryProductName: "Product Name",
    fullCreateMandatoryCategory: "Category",
    fullCreateStopPurchase: "Stop purchase",
    fullCreateHideInPos: "Hide in POS",
    fullCreateRequiresExpiry: "Requires Expiry",
    fullCreateNonExpiry: "Non-Expiry",
    fullCreateNonRefundable: "Non-Refundable",
    fullCreatePublishProduct: "Publish Product",
    fullCreateCreateProduct: "Create Product",
    fullCreateCreateAndAddNew: "Create & Add New",
    fullCreateSuccessTitle: "Product created",
    fullCreateSuccessDescription:
      "Your product has been created successfully. Do you want to create another product now?",
    fullCreateCreateNow: "Create now",
    fullCreateSkipToProducts: "Skip to your products page",
    fullCreateProTipTitle: "Pro Tip",
    fullCreateProTipDescription:
      "Complete all fields to ensure optimal inventory tracking and reporting accuracy.",
    fullViewPageTitle: "View Product",
    fullViewPageSubtitle:
      "Review complete product details. Switch to edit mode to update data.",
    fullViewEnableEdit: "Enable Edit",
    fullViewSaveChanges: "Save Changes",
    fullViewReadModeHint:
      "Read mode is active. Click Enable Edit to modify product details.",
    fullViewBatchesManagement: "Batches Management",
    fullViewBarcodeManagement: "Barcode Management",
    fullViewAddBarcode: "Add Another Barcode",
    fullViewPrimaryBarcode: "Primary Barcode",
    fullViewBoxBarcode: "Box Barcode",
    fullViewEditModeEnabled: "Edit mode enabled",
    fullViewReadModeEnabled: "Read mode enabled",

    // Stock History Page
    searchAdjustmentHistory:
      "Search by adjustment ID, user, status, or product name...",
    stockId: "Stock ID",
    createdAt: "Created At",
    createdUser: "Created User",
    updatedAt: "Updated At",
    totalNumberOfProducts: "Total Number of Products",
    autoMigrated: "Auto migrated",
    failedMigrated: "Failed migrated",
    viewEditDetails: "View & Edit Details",
    viewStockUpdateDetails: "View Stock Update Details",
    viewStockUpdateDetailsDescription:
      "Review the stock update rows in the same table experience used for manual stock updates.",
    backToHistory: "Back to History",
    exportReport: "Export Report",

    // Import Dialog
    updateStockTitle: "Update Stock",
    uploadInventoryDescription:
      "Upload your inventory file with AI-powered migration",
    uploadProductsFile: "Upload your products file",
    excelCsvFormat: "Excel or CSV format • Maximum 25MB",
    dropFileHere: "Drop your file here",
    orClickBrowse: "or click below to browse",
    chooseFileComputer: "Choose File from Computer",
    fileReadyUpload: "File ready to upload",
    chooseDifferentFile: "Choose different file",
    whatInfoNeeded: "What information do you need?",
    required: "Required:",
    optional: "Optional:",
    productNameField: "Product Name",
    priceField: "Price",
    expiryDateField: "Expiry Date",
    quantityField: "Quantity",
    batchNumberField: "Batch Number",
    uploadOptions: "Upload Options",
    configureBeforeUpload: "Configure before upload",
    matchAumetProducts: "Match Aumet Products",
    autoFillProductDetails:
      "Automatically fill in product details from Aumet database",
    autoCreateBarcodes: "Auto-Create Barcodes",
    generateBarcodesForProducts: "Generate barcodes for products without them",
    resetOldStock: "Reset Old Stock",
    clearExistingStock:
      "Clear all existing stock for products in this file before adding new stock",
    setStockToZero: "Set existing stock to zero before upload",
    downloadSample: "Download Template",
    getTemplate:
      "Download the current inventory format with matching sample rows",
    addManually: "Add Manually",
    enterOneByOne: "Enter products one by one",
    viewTour: "View Tour",
    uploadProcess: "Upload & Process",
    processingImport: "Processing inventory...",
    generate: "Generate",
    rewardTitle: "Congratulations!",
    rewardSubtitle: "You've earned a reward",
    rewardReadySubtitle: "Your inventory is ready to use in Pulse!",
    rewardWalletMessage:
      "Added JOD 3.5 to your wallet for Upload Your Inventory",
    rewardReadyMessage:
      "Your inventory dashboard is now filled and ready. We also added JOD 3.5 to your wallet for uploading your inventory.",
    rewardProgressTitle: "Progress to JOD 35 Reward",
    rewardActionsNeeded: "4 more actions needed",
    rewardCompleteActions: "Complete these actions:",
    rewardActionPosTransactions: "Make 5 POS Transactions",
    rewardActionStartSelling: "Start Selling on P2P",
    rewardActionBuyConfirm: "Buy & Confirm P2P Order",
    rewardActionConfirmMarketplace:
      "Confirm Marketplace Order as Purchased Automatically",
    rewardContinue: "Continue",
    inventoryReadyBadge: "Inventory ready",
    inventoryReadyTitle: "Start selling now",
    inventoryReadyDescription:
      "Your inventory is live and ready for your first sale.",
    inventoryReadyCta: "Open Point of Sales",
    inventoryOnboardingBadge: "Inventory Setup",
    inventoryOnboardingTitle: "Moving to Pulse is now effortless",
    inventoryOnboardingDescription:
      "You only need one thing: your inventory Excel file. Upload it once, and Pulse automatically transfers your products, quantities, and batches into Aumet.",
    inventoryOnboardingPrimaryCta: "Go Live with My Inventory",
    inventoryOnboardingSecondaryCta: "Add Products Manually",
    inventoryOnboardingPrimaryCtaHint: "Upload Excel or CSV file",
    inventoryOnboardingSecondaryCtaHint: "Add products one by one",
    inventoryOnboardingStepOneTitle: "Upload your file",
    inventoryOnboardingStepOneDescription:
      "Use your Excel or CSV inventory sheet.",
    inventoryOnboardingStepTwoTitle: "Smart auto-matching",
    inventoryOnboardingStepTwoDescription:
      "Pulse automatically matches products, quantities, and batches.",
    inventoryOnboardingStepThreeTitle: "Start selling immediately",
    inventoryOnboardingStepThreeDescription:
      "Your inventory becomes ready for Marketplace and P2P in seconds.",
    inventoryOnboardingPreviewLabel: "What happens next",
    inventoryOnboardingPreviewTitle: "Your pharmacy goes live instantly",
    inventoryOnboardingPreviewDescription:
      "Once your file is uploaded and verified, your inventory is automatically ready inside Pulse.",
    inventoryOnboardingPreviewBenefitsLabel: "You can immediately:",
    inventoryOnboardingBenefitOne: "Start selling directly on Point of Sales",
    inventoryOnboardingBenefitTwo: "Start selling through P2P",
    inventoryOnboardingBenefitThree: "Buy products from other pharmacies",
    inventoryOnboardingBenefitFour: "Manage your inventory from one place",
    inventoryOnboardingTransitionTitle: "Leave the old system behind.",
    inventoryOnboardingTransitionDescription:
      "We simplified the transition so you can move fast and start growing.",
    inventoryOnboardingFlowTitle: "From upload to live in just a few seconds",
    inventoryOnboardingFlowStepOne: "File uploaded",
    inventoryOnboardingFlowStepTwo: "Smart matching",
    inventoryOnboardingFlowStepThree: "Inventory ready",
    inventoryOnboardingFlowStepFour: "Marketplace activated",
    inventoryOnboardingFlowClosingTitle: "Ready. Set. Grow.",
    inventoryOnboardingFlowClosingDescription: "Welcome to Pulse on Aumet.",

    // Filters
    categoryFilter: "Category",
    filterSelectCategory: "Select a category",
    stockRange: "Stock Range",
    selectStockRange: "Select Stock Range",
    expiryStatus: "Expiry Status",
    selectExpiryStatus: "Select Expiry Status",
    agingLastSale: "Aging last sale",
    selectAgingLastSale: "Select Aging last sale",
    selectStatus: "Select Status",
    reset: "Reset",
    apply: "Apply",
    createdDateRange: "Created Date Range",
    selectDateRange: "Select date range",
    createdUserFilter: "Created User",
    allUsers: "All Users",
    allStatus: "All Status",

    // Inventory — product categories (pharmacy sample)
    categoryGastrointestinal: "Gastrointestinal",
    categoryAntibiotic: "Antibiotics",
    categoryCardiovascular: "Cardiovascular",
    categoryVitamins: "Vitamins & Supplements",
    categoryOtc: "OTC & Allergy",
    categoryDiabetes: "Diabetes",
    categoryDermatology: "Dermatology",
    categoryAnalgesic: "Analgesics & Antipyretics",

    // Inventory — line statuses
    productStatusExpiringSoon: "Expiring Soon",
    productStatusExpired: "Expired",
    productStatusLowStock: "Low Stock",
    productStatusOutOfStock: "Out of Stock",

    // Inventory — table footer (10 demo products)
    inventoryTablePaginationSummary: "Showing 1 to 10 of 10 results",
    inventoryTableAllOnPage: "All 10 results on this page",

    // Update Stock page (stats, adjustments table, footer)
    statTotalAdjustments: "Total Adjustments",
    statConfirmed: "Confirmed",
    statInProgress: "In Progress",
    statFailedCancelled: "Failed / Cancelled",
    adjustmentStatusDraft: "Draft",
    adjustmentStatusPending: "Pending",
    adjustmentStatusProcessing: "Processing",
    adjustmentStatusConfirmed: "Confirmed",
    adjustmentStatusReversal: "Reversal",
    adjustmentStatusFailed: "Failed",
    cancelAdjustment: "Cancel Adjustment",
    actionNotAvailable: "Action not available",
    adjustmentOverview: "Adjustment overview",
    adjustmentOverviewDescription:
      "Quick view of the most important stock adjustment outcomes.",
    adjustmentCountLabel: "Records",
    undoAction: "Undo Action",
    adjustmentStatusAiProcessing: "AI processing",
    adjustmentStatusCancelled: "Cancelled",
    notAvailableMark: "—",
    stockHistoryPaginationSummary: "Showing 1–4 of 25 results",
    lastStockAdjustmentPrefix: "Last stock adjustment:",
    userSarahWilson: "Dr. Sarah Wilson",
    userAhmedRashid: "Ahmed Al-Rashid",
    userFatimaHassan: "Fatima Hassan",
    breadcrumbSeparator: "›",
    paginationPreviousPage: "Previous page",
    paginationNextPage: "Next page",
  },
  ar: {
    all: "الكل",
    // Navbar
    dashboard: "لوحة التحكم",
    pointOfSale: "نقطة البيع",
    stocks: "المخزون",
    pos: "نقطة البيع",
    inventory: "الجرد",
    marketplace: "السوق",
    purchase: "المشتريات",
    sellerPXP: "البائع PXP",
    customers: "العملاء",
    reports: "التقارير",
    settings: "الإعدادات",

    // Inventory Menu
    yourProducts: "منتجاتك",
    inventoryProductsList: "قائمة منتجات المخزون",
    createProduct: "إنشاء منتج",
    updateStock: "تحديث المخزون",
    manualUpdateStock: "تحديث المخزون يدوياً",
    openingStock: "المخزون الافتتاحي",
    createStockAdjustment: "إنشاء تعديل المخزون",
    inventoryAdjustmentHistory: "سجل تعديلات المخزون",
    printBarcode: "طباعة الباركود",
    addProduct: "إضافة منتج",
    browseAumetCore: "استعراض Aumet Core",
    myProducts: "منتجاتي",
    newProduct: "منتج جديد",
    chooseProductSourceDescription:
      "اختر مصدر المنتج الذي تريد إضافته في تحديث المخزون اليدوي.",
    sourceAumetCore: "Aumet Core",
    sourceAumetCoreDescription: "استعرض منتجات الكتالوج الجاهزة من Aumet Core.",
    sourceMyProducts: "منتجاتي",
    sourceMyProductsDescription: "اختر منتجات موجودة بالفعل في مخزونك.",
    sourceNewProduct: "منتج جديد",
    sourceNewProductDescription:
      "أنشئ منتجاً مخصصاً جديداً وأضفه مباشرة إلى الجدول.",
    myProductsDescription:
      "استعرض المنتجات الموجودة بالفعل في مخزونك وأضفها إلى جدول التحديث اليدوي.",
    searchMyProducts:
      "ابحث بالرمز أو اسم المنتج أو الباركود أو الدفعة أو المستودع...",
    noMyProductsFound: "لم يتم العثور على منتجات في المخزون",
    selectProductsFromInventory:
      "اختر منتجاً أو أكثر من مخزونك لإضافته إلى جدول التحديث اليدوي.",
    newProductDescription:
      "أنشئ منتجاً مخصصاً غير موجود في Aumet Core أو في مخزونك.",
    enterProductCode: "أدخل رمز المنتج",
    enterBarcode: "أدخل الباركود",
    productNameEn: "اسم المنتج بالإنجليزية",
    productNameAr: "اسم المنتج بالعربية",
    enterProductNameEn: "أدخل اسم المنتج باللغة الإنجليزية",
    enterProductNameAr: "أدخل اسم المنتج باللغة العربية",
    productCodeAlreadyExists: "تمت إضافة رمز هذا المنتج بالفعل إلى الجدول.",
    customProductWillBeAddedToTable:
      "سيتم إضافة هذا المنتج كصف طبيعي قابل للتعديل داخل جدول التحديث اليدوي.",
    batches: "الدفعات",
    viewBatches: "عرض الدفعات",
    collapse: "طي",
    expandBatches: "توسيع الدفعات",
    collapseBatches: "طي الدفعات",
    productMasterAndBatches: "بيانات المنتج والدفعات",
    editProductAndBatchDetails:
      "قم بتعديل بيانات المنتج ومراجعة تفاصيل المخزون على مستوى الدفعات.",
    selectBatchesOptional: "اختر الدفعات (اختياري)",
    leaveWithoutBatchesToCreateNew:
      "اترك الاختيار بدون دفعات لإنشاء دفعة جديدة في التحديث اليدوي للمخزون.",
    addNewBatch: "إضافة دفعة جديدة",
    newBatch: "دفعة جديدة",
    batchNumber: "رقم الدفعة",
    batchDetails: "تفاصيل الدفعة",
    existingBatchesCanBeEdited:
      "قم بتعديل الدفعات الحالية، أو إزالة ما لا تريد، أو إضافة دفعة جديدة.",
    addBatch: "إضافة دفعة",
    editExistingBatch: "تعديل دفعة موجودة",
    selectExistingBatch: "اختر دفعة موجودة",
    chooseBatchToEditAndAdd: "اختر دفعة لتعديلها وإضافتها مباشرة.",
    linked: "مرتبط",
    notLinked: "غير مرتبط",
    deleteProduct: "حذف المنتج",
    noBatchRowsYet: "لا توجد صفوف دفعات بعد.",
    addExistingOrCreateNewBatch: "أضف دفعة موجودة أو أنشئ دفعة جديدة.",

    productSource: "المصدر",
    "productSource.core": "Aumet Core",
    "productSource.inventory": "منتجاتي",
    "productSource.custom": "منتج جديد",
    aumetCoreProducts: "منتجات Aumet Core",
    aumetCoreProductsDescription:
      "استعرض المنتجات الصيدلانية الجاهزة وأضفها إلى جدول التحديث اليدوي.",
    searchAumetCoreProducts:
      "ابحث بالرمز أو اسم المنتج أو الباركود أو الشركة المصنّعة...",
    selectedItems: "محدد",
    manufacturer: "الشركة المصنّعة",
    alreadyAdded: "تمت إضافته مسبقاً",
    noAumetCoreProductsFound: "لم يتم العثور على منتجات في Aumet Core",
    selectProductsToAddToManualStock:
      "اختر منتجاً أو أكثر لإضافته إلى جدول التحديث اليدوي.",
    addSelectedProducts: "إضافة المنتجات المحددة",
    manualUpdateStockDescription:
      "قم بتحديث المخزون يدوياً للمنتجات المحددة من خلال جدول قابل للتعديل.",
    manualStockOptions: "خيارات التحديث اليدوي للمخزون",
    configureBeforeManualUpdate: "قم بالإعداد قبل التحديث اليدوي",
    searchManualStockTable: "ابحث داخل المنتجات المحددة...",
    currentStock: "المخزون الحالي",
    adjustmentType: "نوع التعديل",
    stockTypeUpdate: "نوع تحديث المخزون",
    stockIn: "إدخال مخزون",
    stockOut: "إخراج مخزون",
    newStockQty: "كمية المخزون الجديدة",
    newStockLevel: "المخزون الجديد",
    adjustmentAdd: "إضافة",
    adjustmentSubtract: "طرح",
    adjustmentSet: "تعيين إلى",
    enterAdjustmentReason: "أدخل سبب التعديل...",
    manualStockRowsCount: "عدد الصفوف:",
    saveAdjustments: "حفظ التعديلات",
    saveAsDraft: "حفظ كمسودة",
    noProductsAddedYet: "لم تتم إضافة منتجات بعد",
    manualStockEmptyStateDescription:
      "استعرض منتجات Aumet Core وأضفها هنا لبدء تحديث المخزون يدوياً.",
    loadingMoreProducts: "جارٍ تحميل المزيد من المنتجات...",

    // Buttons
    createNew: "إنشاء جديد",
    checkAdjustmentHistory: "التحقق من سجل التعديلات",
    stockHistory: "سجل تعديل المخزون",
    stockAdjustment: "تعديل المخزون",
    review: "مراجعة",
    filters: "الفلاتر",
    export: "تصدير",

    // Stats
    totalProducts: "إجمالي المنتجات",
    activeProductsInInventory: "المنتجات النشطة في المخزون",
    expiringsSoon: "تنتهي قريباً",
    productsExpiringsNext90Days: "المنتجات التي تنتهي في الـ 90 يوماً القادمة",
    lowStock: "مخزون منخفض",
    productsBelowMinimumLevel: "المنتجات تحت الحد الأدنى",
    stagnantProducts: "منتجات راكدة",
    productsNoSales90Days: "منتجات بدون مبيعات في آخر 90+ يوماً",

    // Bulk Stocks Page
    bulkStocksHistory: "سجل تعديلات المخزون",
    trackStocksMovements:
      "تتبع جميع حركات المخزون والتغييرات المجراة على مستويات مخزونك",
    updateYourStock: "تحديث المخزون",
    uploadStockFile: "رفع ملف المخزون",
    createManualList: "إنشاء قائمة يدوية",

    // Cards
    receiveMarketplacePurchaseOrders: "استلام طلبات شراء السوق",
    new: "جديد",
    createNewPurchaseOrder: "إنشاء طلب شراء جديد",
    lastAdded: "آخر إضافة",
    daysAgo: "أيام مضت",

    // Search & Table
    searchByNameIdBarcodeHatch: "البحث بالاسم، المعرف، الباركود، الدفعة...",
    code: "الرمز",
    productName: "اسم المنتج",
    barcode: "الباركود",
    category: "الفئة",
    lotBatch: "الدفعة",
    expiry: "انتهاء الصلاحية",
    lastSale: "آخر بيع",
    jod: "د.أ",
    stockQty: "كمية المخزون",
    avgCostPrice: "متوسط سعر التكلفة",
    sellPrice: "سعر البيع",
    tax: "الضريبة %",
    warehouseLocation: "موقع المستودع",
    status: "الحالة",
    actions: "الإجراءات",
    noSales: "لا مبيعات",

    // Pagination
    showing: "عرض",
    to: "إلى",
    of: "من",
    results: "نتيجة",
    show: "عرض",
    perPage: "لكل صفحة",
    allResultsOnThisPage: "جميع النتائج 2 في هذه الصفحة",

    // Footer
    poweredByPulse: "مدعوم من Pulse - نبض صيدليتك",
    startTour: "بدء الجولة",
    help: "مساعدة",

    // Create Product Dialog
    quickNewProductCreation: "إنشاء منتج جديد سريع",
    quickAddYourProduct: "أضف منتجك بسرعة",
    fillInTheDetailsBelow: "املأ التفاصيل أدناه",
    searchAumetProducts: "البحث في منتجات أوميت",
    searchProductName: "ابحث عن اسم المنتج",
    generateBarcode: "توليد",
    enterOrScanBarcode: "أدخل أو امسح الباركود",
    selectCategory: "اختر الفئة",
    medicine: "دواء",
    supplement: "مكمل غذائي",
    equipment: "معدات",
    unitType: "نوع الوحدة",
    selectUnit: "الوحدة",
    tablet: "قرص",
    capsule: "كبسولة",
    bottle: "زجاجة",
    box: "علبة",
    count: "العدد",
    price: "السعر",
    sellingPrice: "سعر البيع",
    taxRate: "الضريبة",
    productDetails: "تفاصيل المنتج",
    firstBatchOptional: "الدفعة الأولى (اختياري)",
    addInitialStock: "إضافة مخزون أولي",
    warehouse: "المستودع",
    main: "الرئيسي",
    expiryDate: "تاريخ الانتهاء",
    selectDate: "اختر التاريخ",
    qty: "الكمية",
    cost: "التكلفة",
    reason: "السبب",
    selectReason: "اختر السبب",
    newStock: "مخزون جديد",
    restock: "إعادة تخزين",
    addAnotherBatch: "إضافة دفعة أخرى",
    moreOptions: "خيارات أكثر",
    needMoreFields: "تحتاج المزيد من الحقول؟ انتقل إلى الصفحة الكاملة",
    back: "رجوع",
    next: "التالي",
    backToChooseProductSource: "الرجوع لاختيار مصدر المنتج",
    cancel: "إلغاء",
    saveProduct: "حفظ المنتج",
    fullCreatePageTitle: "إنشاء منتج كامل",
    fullCreatePageSubtitle:
      "أنشئ ملف منتج كامل مع التصنيف والتسعير والوسائط وإعدادات الظهور.",
    fullCreateBreadcrumbCatalog: "الكتالوج",
    fullCreateBreadcrumbProducts: "المنتجات",
    fullCreateBreadcrumbCreateNew: "إنشاء جديد",
    fullCreateSaveAndNew: "حفظ وإنشاء جديد",
    fullCreateSaveAndExit: "حفظ وخروج",
    fullCreateProductType: "نوع المنتج",
    fullCreateNavBasicInfo: "المعلومات الأساسية",
    fullCreateNavClassification: "التصنيف",
    fullCreateNavUnitsMix: "الوحدات والتركيب",
    fullCreateNavPricingTax: "السعر والضريبة",
    fullCreateNavMedia: "الوسائط",
    fullCreateNavVisibility: "الظهور",
    fullCreateBasicInformation: "المعلومات الأساسية",
    fullCreateTypeStorable: "قابل للتخزين",
    fullCreateTypeService: "خدمة",
    fullCreateTypeConsumable: "استهلاكي",
    fullCreateBarcodePlaceholder: "أدخل الباركود أو رمز المنتج",
    fullCreateAdditionalLanguage: "لغة إضافية",
    fullCreateAdditionalLanguageNone: "لا يوجد",
    fullCreateAdditionalLanguageArabic: "العربية",
    fullCreateAdditionalLanguageFrench: "الفرنسية",
    fullCreateDefaultLanguage: "اللغة الافتراضية",
    fullCreateDefaultLanguageEnglish: "الإنجليزية",
    fullCreateDefaultLanguageArabic: "العربية",
    fullCreateDefaultLanguageFrench: "الفرنسية",
    fullCreateDescription: "الوصف",
    fullCreateDescriptionPlaceholder: "وصف مختصر للمنتج...",
    fullCreateClassification: "التصنيف",
    fullCreateBrandName: "اسم العلامة التجارية",
    fullCreateBrandNamePlaceholder: "أدخل اسم العلامة التجارية",
    fullCreateVendor: "المورد",
    fullCreateVendorDirectSource: "دايركت سورس",
    fullCreateVendorGlobalLogistics: "جلوبال لوجيستكس",
    fullCreateManufacturer: "الشركة المصنّعة",
    fullCreateUnitsAndComposition: "الوحدات والتركيب",
    fullCreateActiveIngredient: "المادة الفعالة",
    fullCreateActiveIngredientsPlural: "المواد الفعالة",
    fullCreateSearchPlaceholder: "بحث...",
    fullCreateAddIngredient: "إضافة مادة",
    fullCreateDosageForm: "الشكل الدوائي",
    fullCreateUomConfiguration: "إعدادات وحدات القياس",
    fullCreateUomUnitMeasure: "وحدة القياس",
    fullCreateUomPack: "باكيت",
    fullCreateUomUnit: "وحدة",
    fullCreatePackSize: "حجم العبوة",
    fullCreatePricingAndTax: "السعر والضريبة",
    fullCreateRetailPrice: "سعر البيع",
    fullCreateDiscount: "نسبة الخصم %",
    fullCreateProductMedia: "وسائط المنتج",
    fullCreateUploadFiles: "رفع ملفات",
    fullCreateImageUrl: "رابط الصورة",
    fullCreateUploadHintMain: "انقر للرفع أو اسحب وأفلت",
    fullCreateUploadHintSub:
      "PNG أو JPG أو WEBP (حتى 5MB). يوصى بمقاس 800x800 بكسل.",
    fullCreateVisibilityTitle: "الحالة والظهور",
    fullCreateStatusActions: "الحالة والإجراءات",
    fullCreateMandatoryFields: "الحقول الإلزامية",
    fullCreateMandatoryProductType: "نوع المنتج",
    fullCreateMandatoryBarcodeSku: "الباركود/الرمز",
    fullCreateMandatoryProductName: "اسم المنتج",
    fullCreateMandatoryCategory: "الفئة",
    fullCreateStopPurchase: "إيقاف الشراء",
    fullCreateHideInPos: "إخفاء في نقطة البيع",
    fullCreateRequiresExpiry: "يتطلب تاريخ انتهاء",
    fullCreateNonExpiry: "غير منتهي الصلاحية",
    fullCreateNonRefundable: "غير قابل للإرجاع",
    fullCreatePublishProduct: "نشر المنتج",
    fullCreateCreateProduct: "إنشاء المنتج",
    fullCreateCreateAndAddNew: "إنشاء وإضافة جديد",
    fullCreateSuccessTitle: "تم إنشاء المنتج",
    fullCreateSuccessDescription:
      "تم إنشاء المنتج بنجاح. هل تريد إنشاء منتج آخر الآن؟",
    fullCreateCreateNow: "إنشاء الآن",
    fullCreateSkipToProducts: "تخطي إلى صفحة منتجاتك",
    fullCreateProTipTitle: "نصيحة",
    fullCreateProTipDescription:
      "إكمال كل الحقول يساعد على تتبع المخزون بدقة وتحسين تقارير الأداء.",
    fullViewPageTitle: "عرض المنتج",
    fullViewPageSubtitle:
      "راجع تفاصيل المنتج كاملة. فعّل وضع التعديل لتحديث البيانات.",
    fullViewEnableEdit: "تفعيل التعديل",
    fullViewSaveChanges: "حفظ التغييرات",
    fullViewReadModeHint:
      "وضع القراءة مفعّل. اضغط تفعيل التعديل لتغيير بيانات المنتج.",
    fullViewBatchesManagement: "إدارة الدفعات",
    fullViewBarcodeManagement: "إدارة الباركود",
    fullViewAddBarcode: "إضافة باركود آخر",
    fullViewPrimaryBarcode: "الباركود الرئيسي",
    fullViewBoxBarcode: "باركود العلبة",
    fullViewEditModeEnabled: "وضع التعديل مفعّل",
    fullViewReadModeEnabled: "وضع القراءة مفعّل",

    // Stock History Page
    searchAdjustmentHistory:
      "البحث بمعرف التعديل، المستخدم، الحالة، أو اسم المنتج...",
    stockId: "معرف المخزون",
    createdAt: "تاريخ الإنشاء",
    createdUser: "المستخدم المنشئ",
    updatedAt: "تاريخ التحديث",
    totalNumberOfProducts: "إجمالي عدد المنتجات",
    autoMigrated: "تم الترحيل تلقائياً",
    failedMigrated: "فشل الترحيل",
    viewEditDetails: "عرض وتعديل التفاصيل",
    viewStockUpdateDetails: "عرض تفاصيل تحديث المخزون",
    viewStockUpdateDetailsDescription:
      "راجع صفوف تحديث المخزون بنفس تجربة الجدول المستخدمة في التحديث اليدوي للمخزون.",
    backToHistory: "العودة إلى السجل",
    exportReport: "تصدير التقرير",

    // Import Dialog
    updateStockTitle: "تحديث المخزون",
    uploadInventoryDescription:
      "رفع ملف المخزون الخاص بك مع الترحيل المدعوم بالذكاء الاصطناعي",
    uploadProductsFile: "رفع ملف المنتجات الخاص بك",
    excelCsvFormat: "صيغة Excel أو CSV • الحد الأقصى 25 ميجابايت",
    dropFileHere: "ضع ملفك هنا",
    orClickBrowse: "أو انقر أدناه للتصفح",
    chooseFileComputer: "اختر ملف من الكمبيوتر",
    fileReadyUpload: "الملف جاهز للرفع",
    chooseDifferentFile: "اختر ملف مختلف",
    whatInfoNeeded: "ما المعلومات التي تحتاجها؟",
    required: "مطلوب:",
    optional: "اختياري:",
    productNameField: "اسم المنتج",
    priceField: "السعر",
    expiryDateField: "تاريخ الانتهاء",
    quantityField: "الكمية",
    batchNumberField: "رقم الدفعة",
    uploadOptions: "خيارات الرفع",
    configureBeforeUpload: "تكوين قبل الرفع",
    matchAumetProducts: "مطابقة منتجات أوميت",
    autoFillProductDetails: "ملء تفاصيل المنتج تلقائياً من قاعدة بيانات أوميت",
    autoCreateBarcodes: "إنشاء باركود تلقائي",
    generateBarcodesForProducts: "توليد باركود للمنتجات التي لا تحتوي عليه",
    resetOldStock: "إعادة تعيين المخزون القديم",
    clearExistingStock:
      "مسح جميع المخزون الموجود للمنتجات في هذا الملف قبل إضافة مخزون جديد",
    setStockToZero: "تعيين المخزون الموجود إلى الصفر قبل الرفع",
    downloadSample: "تنزيل القالب",
    getTemplate: "نزّل تنسيق المخزون الحالي مع صفوف مطابقة كنموذج",
    addManually: "إضافة يدوياً",
    enterOneByOne: "إدخال المنتجات واحداً تلو الآخر",
    viewTour: "عرض الجولة",
    uploadProcess: "رفع ومعالجة",
    processingImport: "جارٍ معالجة المخزون...",
    generate: "توليد",
    rewardTitle: "تهانينا!",
    rewardSubtitle: "لقد حصلت على مكافأة",
    rewardReadySubtitle: "أصبح مخزونك جاهزاً للاستخدام في Pulse!",
    rewardWalletMessage: "تمت إضافة 3.5 دينار إلى محفظتك مقابل رفع المخزون",
    rewardReadyMessage:
      "أصبحت لوحة المخزون لديك ممتلئة وجاهزة للاستخدام. كما تمت إضافة 3.5 دينار إلى محفظتك مقابل رفع المخزون.",
    rewardProgressTitle: "التقدم نحو مكافأة 35 دينار",
    rewardActionsNeeded: "تحتاج إلى 4 إجراءات إضافية",
    rewardCompleteActions: "أكمل هذه الإجراءات:",
    rewardActionPosTransactions: "نفّذ 5 عمليات بيع POS",
    rewardActionStartSelling: "ابدأ البيع على P2P",
    rewardActionBuyConfirm: "اشترِ وأكّد طلب P2P",
    rewardActionConfirmMarketplace: "أكّد طلب السوق كمشتَرى تلقائياً",
    rewardContinue: "متابعة",
    inventoryReadyBadge: "المخزون جاهز",
    inventoryReadyTitle: "ابدأ البيع عبر نقاط البيع",
    inventoryReadyDescription:
      "أصبح مخزونك جاهزًا داخل النظام. يمكنك البدء بالبيع عبر نقاط البيع وخدمة مرضاك بثقة.",
    inventoryReadyCta: "فتح نقاط البيع",
    inventoryOnboardingBadge: "إعداد المخزون",
    inventoryOnboardingTitle: "الانتقال إلى Pulse أصبح أسهل من أي وقت",
    inventoryOnboardingDescription:
      "كل ما تحتاجه هو ملف Excel الخاص بالمخزون. ارفعه مرة واحدة، وسيقوم Pulse تلقائيًا بنقل المنتجات والكميات والتشغيلات إلى Aumet.",
    inventoryOnboardingPrimaryCta: "فعّل مخزوني الآن",
    inventoryOnboardingSecondaryCta: "إضافة المنتجات يدويًا",
    inventoryOnboardingPrimaryCtaHint: "ارفع ملف Excel أو CSV",
    inventoryOnboardingSecondaryCtaHint: "أضف المنتجات واحدًا تلو الآخر",
    inventoryOnboardingStepOneTitle: "ارفع الملف",
    inventoryOnboardingStepOneDescription:
      "استخدم ملف Excel أو CSV الخاص بالمخزون.",
    inventoryOnboardingStepTwoTitle: "المطابقة الذكية التلقائية",
    inventoryOnboardingStepTwoDescription:
      "يقوم Pulse تلقائيًا بمطابقة المنتجات والكميات والتشغيلات.",
    inventoryOnboardingStepThreeTitle: "ابدأ البيع فورًا",
    inventoryOnboardingStepThreeDescription:
      "يصبح مخزونك جاهزًا للماركت بليس وP2P خلال ثوانٍ.",
    inventoryOnboardingPreviewLabel: "ماذا سيحدث بعد ذلك",
    inventoryOnboardingPreviewTitle: "صيدليتك تصبح جاهزة للعمل فورًا",
    inventoryOnboardingPreviewDescription:
      "بمجرد رفع الملف والتحقق منه، يصبح مخزونك جاهزًا تلقائيًا داخل Pulse.",
    inventoryOnboardingPreviewBenefitsLabel: "يمكنك مباشرة:",
    inventoryOnboardingBenefitOne: "ابدأ البيع مباشرة عبر نقاط البيع",
    inventoryOnboardingBenefitTwo: "ابدأ البيع عبر P2P",
    inventoryOnboardingBenefitThree: "اشترِ المنتجات من صيدليات أخرى",
    inventoryOnboardingBenefitFour: "إدارة مخزونك من مكان واحد",
    inventoryOnboardingTransitionTitle: "اترك النظام القديم خلفك.",
    inventoryOnboardingTransitionDescription:
      "بسّطنا الانتقال لتتحرك بسرعة وتبدأ بالنمو.",
    inventoryOnboardingFlowTitle: "من الرفع إلى الجاهزية خلال ثوانٍ",
    inventoryOnboardingFlowStepOne: "تم رفع الملف",
    inventoryOnboardingFlowStepTwo: "مطابقة ذكية",
    inventoryOnboardingFlowStepThree: "المخزون جاهز",
    inventoryOnboardingFlowStepFour: "تم تفعيل الماركت بليس",
    inventoryOnboardingFlowClosingTitle: "جاهز. انطلق. نمِّ أعمالك.",
    inventoryOnboardingFlowClosingDescription: "مرحبًا بك في Pulse على Aumet.",

    // Filters
    categoryFilter: "الفئة",
    filterSelectCategory: "اختر الفئة",
    stockRange: "نطاق المخزون",
    selectStockRange: "اختر نطاق المخزون",
    expiryStatus: "حالة الصلاحية",
    selectExpiryStatus: "اختر حالة الصلاحية",
    agingLastSale: "عمر آخر بيع",
    selectAgingLastSale: "اختر عمر آخر بيع",
    selectStatus: "اختر الحالة",
    reset: "إعادة تعيين",
    apply: "تطبيق",
    createdDateRange: "نطاق تاريخ الإنشاء",
    selectDateRange: "اختر نطاق التاريخ",
    createdUserFilter: "المستخدم المنشئ",
    allUsers: "جميع المستخدمين",
    allStatus: "جميع الحالات",

    // Inventory — product categories (pharmacy sample)
    categoryGastrointestinal: "الجهاز الهضمي",
    categoryAntibiotic: "مضادات حيوية",
    categoryCardiovascular: "القلب والأوعية",
    categoryVitamins: "فيتامينات ومكملات",
    categoryOtc: "بدون وصفة والحساسية",
    categoryDiabetes: "السكري",
    categoryDermatology: "الأمراض الجلدية",
    categoryAnalgesic: "مسكنات وخافضات حرارة",

    // Inventory — line statuses
    productStatusExpiringSoon: "تنتهي قريباً",
    productStatusExpired: "منتهي الصلاحية",
    productStatusLowStock: "مخزون منخفض",
    productStatusOutOfStock: "نفد المخزون",

    // Inventory — table footer (10 demo products)
    inventoryTablePaginationSummary: "عرض 1 إلى 10 من 10 نتائج",
    inventoryTableAllOnPage: "جميع الـ 10 نتائج في هذه الصفحة",

    // Update Stock page (stats, adjustments table, footer)
    statTotalAdjustments: "إجمالي التعديلات",
    statConfirmed: "مؤكد",
    statInProgress: "قيد التنفيذ",
    statFailedCancelled: "فشل / ملغى",
    adjustmentStatusDraft: "مسودة",
    adjustmentStatusPending: "قيد الانتظار",
    adjustmentStatusProcessing: "قيد المعالجة",
    adjustmentStatusConfirmed: "مؤكد",
    adjustmentStatusReversal: "عكس المخزون",
    adjustmentStatusFailed: "فشل",
    cancelAdjustment: "إلغاء التعديل",
    actionNotAvailable: "الإجراء غير متاح",
    adjustmentOverview: "نظرة عامة على التعديلات",
    adjustmentOverviewDescription: "عرض سريع لأهم نتائج تعديلات المخزون.",
    adjustmentCountLabel: "السجلات",
    undoAction: "تراجع عن العملية",
    adjustmentStatusAiProcessing: "معالجة بالذكاء الاصطناعي",
    adjustmentStatusCancelled: "ملغى",
    notAvailableMark: "—",
    stockHistoryPaginationSummary: "عرض 1–4 من 25 نتيجة",
    lastStockAdjustmentPrefix: "آخر تعديل للمخزون:",
    userSarahWilson: "د. سارة ويلسون",
    userAhmedRashid: "أحمد الراشد",
    userFatimaHassan: "فاطمة حسن",
    breadcrumbSeparator: "›",
    paginationPreviousPage: "الصفحة السابقة",
    paginationNextPage: "الصفحة التالية",
  },
};

const language = ref<Language>("en");

if (typeof window !== "undefined") {
  const saved = window.localStorage.getItem("pulse-language");
  if (saved === "en" || saved === "ar") language.value = saved;
}

watchEffect(() => {
  if (typeof document !== "undefined") {
    document.documentElement.lang = language.value;
    document.documentElement.dir = language.value === "ar" ? "rtl" : "ltr";
  }
  if (typeof window !== "undefined") {
    window.localStorage.setItem("pulse-language", language.value);
  }
});

export function useLanguage() {
  const toggleLanguage = () => {
    language.value = language.value === "en" ? "ar" : "en";
  };
  const t = (key: string): string => {
    const dict = translations[language.value] as Record<string, string>;
    return dict[key] || key;
  };
  const isRTL = computed(() => language.value === "ar");
  return { language, toggleLanguage, t, isRTL };
}
